### ISSUE TITLE
キーワード受信の機能

### ISSUE THREAD

**Issue by Yusk1450** [penguinspizza/server_toyusai_2023#1]
3つのScratchゲームをクリアしたときに表示される「ぶ」「ん」「り」という文字を、べつに作成したHTMLフォームでPOSTリクエストで送信するので、受け取れるようにしてほしい

URI：/keyword
メソッド：POST
パラメタ：word（文字列）

↑のwordの中身が「ぶんり」だったらstatus.jsonの"1"をtrueにする

あと、HTMLをレスポンスできるようにして、正解と不正解で切り分けたい

**Comment by penguinspizza** [comment]
https://github.com/penguinspizza/server_toyusai_2023/commit/9d6f17723741905d5de1446adba977476d1c4003
にて実装しました

HTMLレスポンスは
正解の場合: True
不正解の場合: False
を返します

**Comment by penguinspizza** [comment]
@penguinspizza 
HTMLレスポンスは用意したファイルに差し替える
